site_name: BYU CCE 270
site_url: https://byu-cce270.readthedocs.io/en/latest/
site_description: Course materials for CCE 270 at BYU
site_author: Instructors and TAs of CCE 270 at BYU
repo_url: https://github.com/byu-cce270/content/
favicon: 'images/favicon.ico'
theme:
  name: null
  custom_dir: 'cinder'
nav:
  - Home: index.md
  - Unit 1:
    - Lookups and Match:
      - Homework: unit1/homework/lookups_and_match.md
    - Query Function:
      - Reading: unit1/reading/query_function.md
      - In Class: unit1/exercises/employee_db.md
      - Homework: unit1/homework/safety_db.md
  - Unit 2:
    - Variables:
      - Reading: unit2/reading/variables.md
      - In Class: unit2/exercises/variables.md
      - Homework: unit2/homework/variables.md
    - Lists:
      - Reading: unit2/reading/lists.md
      - In Class: unit2/homework/lists.md
      - Homework: unit2/exercises/lists.md